CREATE TABLE "users"
(
    "id"                  BIGINT generated by default as identity NOT NULL,
    "email"               VARCHAR(255)                            NOT NULL UNIQUE,
    "keycloak_user_id"    VARCHAR(255),
    "role"                VARCHAR(255),
    "first_name"          VARCHAR(255)                            NOT NULL,
    "last_name"           VARCHAR(255)                            NOT NULL,
    "description"         VARCHAR(255),
    "birthday"            DATE NOT NULL
);
ALTER TABLE
    "users"
    ADD PRIMARY KEY ("id");