CREATE TABLE "users"
(
    "id"          BIGINT generated by default as identity NOT NULL,
    "email"       VARCHAR(255)                            NOT NULL UNIQUE,
    "password"    VARCHAR(255)                            NOT NULL,
    "role"        BIGINT                                  NOT NULL,
    "first_name"  VARCHAR(255)                            NOT NULL,
    "last_name"   VARCHAR(255)                            NOT NULL,
    "description" varchar(255),
    "birthday"    TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
ALTER TABLE
    "users"
    ADD PRIMARY KEY ("id");